# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('qBittorrentPortable', 'qBittorrentPortable'),
        ('ffmpeg-8.0.1-essentials_build', 'ffmpeg-8.0.1-essentials_build'),
        ('movielist.json', '.'),
        ('popular-movielist.json', '.'),
        ('genres.json', '.'),
        ('action-movielist.json', '.'),
        ('adventure-movielist.json', '.'),
        ('animation-movielist.json', '.'),
        ('comedy-movielist.json', '.'),
        ('crime-movielist.json', '.'),
        ('documentary-movielist.json', '.'),
        ('drama-movielist.json', '.'),
        ('family-movielist.json', '.'),
        ('fantasy-movielist.json', '.'),
        ('history-movielist.json', '.'),
        ('horror-movielist.json', '.'),
        ('music-movielist.json', '.'),
        ('mystery-movielist.json', '.'),
        ('romance-movielist.json', '.'),
        ('sci-fi-movielist.json', '.'),
        ('science fiction-movielist.json', '.'),
        ('thriller-movielist.json', '.'),
        ('tv movie-movielist.json', '.'),
        ('war-movielist.json', '.'),
        ('western-movielist.json', '.'),
        ('media.db', '.'),
    ],
    hiddenimports=['qbittorrentapi'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='JetFlix',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
